#################################################################
# groups

#! @ChapterInfo `FGAb`, Additive Group
#! @Arguments A
#! @Description `IsFGAb` is the supercategory of `IsAdditiveGroup and IsFGAbElementCollection`.
DeclareCategory( "IsFGAb", IsAdditiveGroup and IsFGAbElementCollection );

DeclareRepresentation( "IsFGAbRep", IsAttributeStoringRep );

#! @ChapterInfo `FGAb`, Additive Group
#! @Arguments A
#! @Returns the underlying matirx of `A`
DeclareAttribute( "UnderlyingMatrix", IsFGAb and IsFGAbRep );

# It returns a FGAb B:B0 -> B1 that B is rectangular diagonal and injective, and the diagonal entries are all greater than 1. 
#! @BeginGroup `SimplifiedFGAb`
#! @ChapterInfo `FGAb`, Additive Group
#! @Arguments A
#! @Returns a `FGAb`
#! @Description We can make a Schmit decompostion `UnderlyingMatrix(A)` to get a diagonal matrix, and discard redundant dimensions.
DeclareAttribute( "SimplifiedFGAb", IsFGAb and IsFGAbRep );

#! @ChapterInfo `FGAb`, Additive Group
#! @Arguments A
#! @Returns the isomorphism to `SimplifiedFGAb` as `FGAbHomomorphism`
#! @Description The input must be a output of `SimplifiedFGAb`.
DeclareAttribute( "ToSimplifiedFGAb", IsFGAb and IsFGAbRep );

#! @ChapterInfo `FGAb`, Additive Group
#! @Arguments A
#! @Returns the isomorphism from `SimplifiedFGAb` as `FGAbHomomorphism`
#! @Description The input must be a output of `SimplifiedFGAb`.
DeclareAttribute( "FromSimplifiedFGAb", IsFGAb and IsFGAbRep );
#! @EndGroup

# FGAb( m )
# It returns the FGAb.
# DeclareOperation( "FGAb", [ IsMatrixOrMatrixObj ] );

# FGAb( v )
# It returns the FGAb.
# v is the diagonal entries.
#! @ChapterInfo `FGAb`, Additive Group
#! @Arguments m
#! @Returns the `FGAb`
#! @Description `m` can be either a `MatrixObj` or a naive matirx. For example, if you want a $\mathbb{Z}_2\oplus \mathbb{Z}_4$, use `FGAb([[2, 0], [0, 4]])`.
DeclareOperation( "FGAb", [ IsVector ] );

# FreeFGAb( n )
# It returns the FGAb.
# n is the dimension.
#! @ChapterInfo `FGAb`, Additive Group
#! @Arguments n
#! @Returns the free `FGAb`, i.e. $\mathbb{Z}^n$
DeclareOperation( "FreeFGAb", [ IsInt ] );

# SubFGAb( A, gens )
#! @BeginGroup `SubFGAb`
#! @ChapterInfo `FGAb`, Additive Group
#! @Arguments A, gens
#! @Returns the `SubFGAb` generated by `gens`
DeclareOperation( "SubFGAb", [ IsFGAb, IsList ] );

#! @ChapterInfo `FGAb`, Additive Group
#! @Arguments A
#! @Returns the canonical inclusion as `FGAbHomomorphism`
#! @Description The input `A` should be the output of `SubFGAb`.
DeclareAttribute( "FromSubFGAb", IsFGAb and IsFGAbRep );
#! @EndGroup

# FGAbElement( A, v )
#! @ChapterInfo `FGAb`, `FGAbElement`
#! @Arguments A, v
#! @Returns a `FGAbElement` in `A`
#! @Description `A` is a `FGAb` and `v` is a vector.
DeclareOperation( "FGAbElement", [ IsFGAb, IsVector ] );

#! @ChapterInfo `FGAb`, Additive Group
#! @Arguments A
#! @Returns a list of generators
#! @Description As `SimplifiedFGAb(a)` gives the ``smallest'' representation of `A`, we can use it as a `IndependentGeneratorsOfAdditiveGroup`.
DeclareAttribute( "IndependentGeneratorsOfAdditiveGroup", IsAdditiveGroup );

# FGAbDirectSum( A, B )
# FGAbDirectSum( list )
#! @BeginGroup `FGAbDirectSum`
#! @ChapterInfo `FGAb`, Additive Group
#! @Arguments A1, A2
DeclareOperation( "FGAbDirectSum", [ IsFGAb, IsFGAb] );
#! @ChapterInfo `FGAb`, Additive Group
#! @Arguments listA
DeclareOperation( "FGAbDirectSum", [ IsList] );
#! @ChapterInfo `FGAb`, Additive Group
#! @Arguments A
#! @Description `FGAbDirectSumInfo` stored a record with `FGAb`, `embeddings`, `projections`. `FGAb` is a list of `FGAb`, `embeddings` and `projections` are lists of canonical maps.
DeclareAttribute( "FGAbDirectSumInfo", IsFGAb, "mutable" );
#! @EndGroup